// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  child: string;
  lg: string;
  md: string;
  skeleton: string;
  'skeleton-loading': string;
  sm: string;
  xl: string;
  xs: string;
}
export const cssExports: CssExports;
export default cssExports;
